version: 2

sources:
  - name: src
    database: testdb
    schema: public
    tables:
      - name: source_customers
      - name: source_orders

  - name: rt
    database: rtk_de
    schema: akozyr
    tables:
      - name: ods_payment
      # - name: source_payments